name: NodeJS with Webpack Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npx webpack

    - name: Push dist subtree
      run: |
        git add dist
        git config --local user.email "56723522+ghost-goblin@users.noreply.github.com"
        git config --local user.name "ghost-goblin"
        git commit -m 'deploy'
        git subtree push --prefix dist origin gh-pages
